drf_writable_nested/mixins.py, tests/serializers.py, tests/test_writable_nested_model_serializer.py
Handling cases where serializer has a custom field that is not on the model by catching FieldDoesNotExist. (fixes #4 )
=> Handle when serializer has a field that's not on the model

CHANGELOG.md, README.md, drf_writable_nested/mixins.py, tests/models.py, tests/serializers.py, tests/test_writable_nested_model_serializer.py
In a lot of cases you need to be able to add and maybe update an existing related object also when creating the base object. Currently this is not possible, all related objects are always created as new even when they exist in the database and their `pk` value is submitted to the serializer. This pull request fixes that. Now all related objects are either updated/added _or_ created for both `create` and `update` actions.
=> Possibility to use existing related objects on create

CHANGELOG.md, drf_writable_nested/mixins.py, tests/models.py, tests/test_writable_nested_model_serializer.py
There was a problem in raising protected error, `join` method failed
because it tried to join instance instead of its str representation (mixins.py, line 270)
<code>
self.fail('cannot_delete_protected', instances=", ".join([str(instance) for instance in instances]))
</code>
Fixed problem, changed User model to provide error situation, added
its test.
=> Fix problem with raising protected error in deleteion

CHANGELOG.md, drf_writable_nested/mixins.py, tests/models.py, tests/serializers.py, tests/test_writable_nested_model_serializer.py
There was a problem for updating models with UUID primary key fields:
instead of updating old instance it created new one and deleted old.
Fixed `prefetch_related_instances` method to use str for uuid primary
keys and its UUID object in instances dict, added new Message model
with its serializer to provide error situation and adjusted `test_update`
to check it.
In real usage UUID pk fields comes in deserialized request query params as strings thats why the problem appears.
=> Fix problem for update models with UUID id fields

drf_writable_nested/mixins.py, tests/test_writable_nested_model_serializer.py
Deleting M2M related objects when the relation is removed is counterintuitive to the M2M concept. E g if you have Users that belongs to Groups, it is a strange use case that you delete the whole Group for everyone when removing one User from it.
=> Don't delete related M2M objects when removing the relation

drf_writable_nested/mixins.py, tests/models.py, tests/serializers.py, tests/test_writable_nested_model_serializer.py
This library currently assumes that the `related_name` field is explicitly set in the foreign key definition. This change gives support to something like this:
```
profile = models.ForeignKey(Profile)  # No `related_name` set
```
=> Support m2m fields that do not have `related_name` specified

drf_writable_nested/mixins.py, tests/serializers.py, tests/test_writable_nested_model_serializer.py
Add check that field exists in `initial_data`
There are may be different cases when some field exists in `validated_data` and does not exists in `initial_data`.
For example, developer may implement `Serializer.validate` method and provide some default values for fields, that were not sent in request.
Also DRF may have different return values for `ListSerializer.get_value` method, which returns `class empty` in case of JSON format, or `[]` for `multipart` request
=> Fix multipart form data request

drf_writable_nested/mixins.py, tests/test_writable_nested_model_serializer.py
This is an updated version of https://github.com/beda-software/drf-writable-nested/pull/29
- Implemented from current master, so no merge conflicts.
- Comments/requests for changes from ruscoder implemented.
- Test updated to pass (with latest master).
- Tested on our codebase.
We're now using the fork for our project, but I'd love to see this in mainline.
=> Allow child one-to-one instances to be updated without providing PK (updated)

drf_writable_nested/mixins.py, tests/models.py, tests/serializers.py, tests/test_writable_nested_model_serializer.py, tests/utils.py
use self.get_initial() instead of self.initial_data()
=> fixed MultiValueDictKeyError for nested_updates on reverse-relations

drf_writable_nested/mixins.py, tests/serializers.py, tests/test_writable_nested_model_serializer.py
When we're trying to create a nested field during a update, we have to perform a "full" validation for the child serializer no mater the parent serializer's update action is "partial" or not.
=> Validate nested field before creating it even in partial update

.travis.yml, setup.py, tox.ini
[`dist: xenial` is needed for Python 3.7+ on Travis CI](https://github.com/travis-ci/travis-ci/issues/9815).
Fixes #62
=> Support Python 3.7

README.md
=> Document 3.7 support in README and add Python versions badge

.travis.yml, README.md, setup.py, tox.ini
@ruscoder Looks like an actual incompatibility with Django 2.2.
*Maybe* related to: https://docs.djangoproject.com/en/2.2/releases/2.2/#permissions-for-proxy-models?
=> Support Django 2.2

drf_writable_nested/mixins.py, tox.ini
Fixed import error in **Django 3.1**
The import error also occurs in **Django 3.1 and DRF 3.10**, so the **Django 3.1 related parts** in the tox setting are separated.
```
py{36,37,38}-dj{31}-drf{311}
```
https://docs.djangoproject.com/en/3.1/releases/3.1/#id1
The compatibility import of **django.core.exceptions.FieldDoesNotExist** in **django.db.models.fields** is removed.
=> FieldDoesNotExist import bug fix (Django 3.1)

.travis.yml, README.md, setup.py
Support for Django 3.1 was added in #114, but CI testing was not added. This PR adds Django 3.1 testing to CI.
=> Test Django 3.1 in CI

.gitignore, README.md, drf_writable_nested/mixins.py, requirements.txt, requirements/base.txt, requirements/test.txt, tests/test_writable_nested_model_serializer.py, tests/urls.py, tests/views.py
When I make a PUT or PATCH request on an object that includes changes to a nested model, the response does not include the changes. 
But when I do a GET on the object after that, it shows the changes. It is making the change, but not returning it in the response.
I've confirmed that adding a `refresh_from_db()` in the update serializer fixes this. It responds with the changes I made, and behaves like I'd expect.
Example:
Models:
```python
class Question(BaseModel):
text = models.CharField(max_length=50)
class Option(BaseModel):
question = models.ForeignKey(
"Question", related_name="options", on_delete=models.CASCADE,
)
text = models.CharField(max_length=50)
```
Serializers:
```python
class OptionSerializer(DynamicFieldsModelSerializer):
class Meta:
model = models.Option
fields = (
"id", …
```
=> Refresh from DB when updating nested object

drf_writable_nested/mixins.py, tests/test_unique_fields_mixin.py
_validate_unique_fields now accounts for partial updates and does not attempt checks on fields if they've not been provided.
=> UniqueFieldsMixin validation optional for partial update

requirements.txt
eliminates `six` dependency by upgrading pytest-django to 4.0 to fix #132
=> Upgrades to `pytest-django==4.0.0`

drf_writable_nested/mixins.py
It's currently possible to extend create and update functionality by just implementing those methods on the child serializer, but deletion is a bit trickier.
This proposed refactor exposes just the place in the code where deletion takes place so that more functionality can be easily added in user code if desired.
For my particular use case, I want to be able to create events and update inventory any time a nested item is deleted. With this new change, I can simply extend ``perform_nested_delete(pks_to_delete, **kwargs)`` to include my functionality and call super() to ensure the deletion takes place as expected.
As a side effect, this enables users to adopt functionality proposed in #103 and #112 until the PRs are accepted/declined.
=> Make nested object deletion extensible

drf_writable_nested/mixins.py, tests/models.py, tests/serializers.py, tests/test_writable_nested_model_serializer.py
Fixes https://github.com/beda-software/drf-writable-nested/issues/165
=> Fix reverse m2m relation update

.github/workflows/build.yaml, tests/serializers.py, tox.ini
I think that the mypy tests are broken (See #183), so fixing them here before.
=> Fix mypy checks

.github/workflows/build.yaml, CHANGELOG.md, README.md, setup.py, tox.ini
=> Add official support for Django 5.1-5.2 and Python 3.13
